// =============================================================================
// LeadGenRentalsHQ - Complete Password Reset (Custom Token via app_metadata)
// =============================================================================
// Verifies a custom password-reset token (generated by send-password-reset and
// stored in the user's app_metadata) then updates the password via the admin API.
//
// This function NEVER calls any Supabase method that triggers built-in emails.
// It uses only admin.auth.admin.getUserById() and admin.auth.admin.updateUser().
//
// Payload: { token: string, new_password: string, uid: string }
// No auth required - the token itself is the proof of identity.
// =============================================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

/** SHA-256 hash of a string, returned as hex. */
async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const hashBuffer = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(hashBuffer)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { token, new_password, uid } = await req.json();

    if (!token || typeof token !== "string") {
      return new Response(
        JSON.stringify({ error: "Reset token is required." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    if (!uid || typeof uid !== "string") {
      return new Response(
        JSON.stringify({ error: "User identifier is required." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    if (!new_password || typeof new_password !== "string" || new_password.length < 6) {
      return new Response(
        JSON.stringify({ error: "Password must be at least 6 characters." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    const adminClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // ── Look up user by ID ─────────────────────────────────────────────
    const { data: userData, error: userError } =
      await adminClient.auth.admin.getUserById(uid);

    if (userError || !userData?.user) {
      console.error("User lookup error:", userError?.message || "user not found");
      return new Response(
        JSON.stringify({ error: "Invalid or expired reset link. Please request a new one." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // ── Verify token against app_metadata ──────────────────────────────
    const meta = userData.user.app_metadata || {};
    const storedHash = meta.reset_token_hash;
    const expiresAt = meta.reset_token_expires_at;

    if (!storedHash || !expiresAt) {
      return new Response(
        JSON.stringify({ error: "No pending password reset. Please request a new one." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // Check expiry
    if (new Date(expiresAt) < new Date()) {
      return new Response(
        JSON.stringify({ error: "This reset link has expired. Please request a new one." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // Verify hash
    const tokenHash = await sha256Hex(token);
    if (tokenHash !== storedHash) {
      return new Response(
        JSON.stringify({ error: "Invalid reset link. Please request a new one." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    // ── Update password & clear token from app_metadata ────────────────
    const { error: updateErr } = await adminClient.auth.admin.updateUser(
      uid,
      {
        password: new_password,
        app_metadata: {
          reset_token_hash: null,
          reset_token_expires_at: null,
        },
      },
    );

    if (updateErr) {
      console.error("Password update error:", updateErr.message);
      return new Response(
        JSON.stringify({ error: "Failed to update password. Please try again." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
      );
    }

    console.log("Password reset completed for user:", uid);

    return new Response(
      JSON.stringify({ success: true }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err) {
    console.error("complete-password-reset error:", err);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
