-- Seed per-city pricing for all sub-niches across the 15 active cities.
-- Prices match the sub-niche defaults; admin can edit individual rows in /admin.
-- Safe to re-run (on conflict do nothing).

insert into ppl_pricing (niche, sub_niche, area, price_per_lead) values

  -- ── HVAC: Installations (Split & Ducted) — $70 ──────────────────────────────
  ('hvac','split_ducted','Brisbane',70.00),
  ('hvac','split_ducted','Gold Coast',70.00),
  ('hvac','split_ducted','Sunshine Coast',70.00),
  ('hvac','split_ducted','Toowoomba',70.00),
  ('hvac','split_ducted','Townsville',70.00),
  ('hvac','split_ducted','Cairns',70.00),
  ('hvac','split_ducted','Sydney',70.00),
  ('hvac','split_ducted','Newcastle',70.00),
  ('hvac','split_ducted','Wollongong',70.00),
  ('hvac','split_ducted','Central Coast',70.00),
  ('hvac','split_ducted','Melbourne',70.00),
  ('hvac','split_ducted','Geelong',70.00),
  ('hvac','split_ducted','Perth',70.00),
  ('hvac','split_ducted','Adelaide',70.00),
  ('hvac','split_ducted','Canberra',70.00),

  -- ── HVAC: Installations & Maintenance — $70 ─────────────────────────────────
  ('hvac','installations_maintenance','Brisbane',70.00),
  ('hvac','installations_maintenance','Gold Coast',70.00),
  ('hvac','installations_maintenance','Sunshine Coast',70.00),
  ('hvac','installations_maintenance','Toowoomba',70.00),
  ('hvac','installations_maintenance','Townsville',70.00),
  ('hvac','installations_maintenance','Cairns',70.00),
  ('hvac','installations_maintenance','Sydney',70.00),
  ('hvac','installations_maintenance','Newcastle',70.00),
  ('hvac','installations_maintenance','Wollongong',70.00),
  ('hvac','installations_maintenance','Central Coast',70.00),
  ('hvac','installations_maintenance','Melbourne',70.00),
  ('hvac','installations_maintenance','Geelong',70.00),
  ('hvac','installations_maintenance','Perth',70.00),
  ('hvac','installations_maintenance','Adelaide',70.00),
  ('hvac','installations_maintenance','Canberra',70.00),

  -- ── Roofing: All Restorations — $70 ─────────────────────────────────────────
  ('roofing','all_restorations','Brisbane',70.00),
  ('roofing','all_restorations','Gold Coast',70.00),
  ('roofing','all_restorations','Sunshine Coast',70.00),
  ('roofing','all_restorations','Toowoomba',70.00),
  ('roofing','all_restorations','Townsville',70.00),
  ('roofing','all_restorations','Cairns',70.00),
  ('roofing','all_restorations','Sydney',70.00),
  ('roofing','all_restorations','Newcastle',70.00),
  ('roofing','all_restorations','Wollongong',70.00),
  ('roofing','all_restorations','Central Coast',70.00),
  ('roofing','all_restorations','Melbourne',70.00),
  ('roofing','all_restorations','Geelong',70.00),
  ('roofing','all_restorations','Perth',70.00),
  ('roofing','all_restorations','Adelaide',70.00),
  ('roofing','all_restorations','Canberra',70.00),

  -- ── Roofing: All Replacements — $85 ─────────────────────────────────────────
  ('roofing','all_replacements','Brisbane',85.00),
  ('roofing','all_replacements','Gold Coast',85.00),
  ('roofing','all_replacements','Sunshine Coast',85.00),
  ('roofing','all_replacements','Toowoomba',85.00),
  ('roofing','all_replacements','Townsville',85.00),
  ('roofing','all_replacements','Cairns',85.00),
  ('roofing','all_replacements','Sydney',85.00),
  ('roofing','all_replacements','Newcastle',85.00),
  ('roofing','all_replacements','Wollongong',85.00),
  ('roofing','all_replacements','Central Coast',85.00),
  ('roofing','all_replacements','Melbourne',85.00),
  ('roofing','all_replacements','Geelong',85.00),
  ('roofing','all_replacements','Perth',85.00),
  ('roofing','all_replacements','Adelaide',85.00),
  ('roofing','all_replacements','Canberra',85.00),

  -- ── Roofing: Tile-to-Metal Replacements — $125 ──────────────────────────────
  ('roofing','tile_metal','Brisbane',125.00),
  ('roofing','tile_metal','Gold Coast',125.00),
  ('roofing','tile_metal','Sunshine Coast',125.00),
  ('roofing','tile_metal','Toowoomba',125.00),
  ('roofing','tile_metal','Townsville',125.00),
  ('roofing','tile_metal','Cairns',125.00),
  ('roofing','tile_metal','Sydney',125.00),
  ('roofing','tile_metal','Newcastle',125.00),
  ('roofing','tile_metal','Wollongong',125.00),
  ('roofing','tile_metal','Central Coast',125.00),
  ('roofing','tile_metal','Melbourne',125.00),
  ('roofing','tile_metal','Geelong',125.00),
  ('roofing','tile_metal','Perth',125.00),
  ('roofing','tile_metal','Adelaide',125.00),
  ('roofing','tile_metal','Canberra',125.00),

  -- ── Renovation: Kitchen Renovations — $95 ───────────────────────────────────
  ('renovation','kitchen','Brisbane',95.00),
  ('renovation','kitchen','Gold Coast',95.00),
  ('renovation','kitchen','Sunshine Coast',95.00),
  ('renovation','kitchen','Toowoomba',95.00),
  ('renovation','kitchen','Townsville',95.00),
  ('renovation','kitchen','Cairns',95.00),
  ('renovation','kitchen','Sydney',95.00),
  ('renovation','kitchen','Newcastle',95.00),
  ('renovation','kitchen','Wollongong',95.00),
  ('renovation','kitchen','Central Coast',95.00),
  ('renovation','kitchen','Melbourne',95.00),
  ('renovation','kitchen','Geelong',95.00),
  ('renovation','kitchen','Perth',95.00),
  ('renovation','kitchen','Adelaide',95.00),
  ('renovation','kitchen','Canberra',95.00),

  -- ── Renovation: Bathroom Renovations — $95 ──────────────────────────────────
  ('renovation','bathroom','Brisbane',95.00),
  ('renovation','bathroom','Gold Coast',95.00),
  ('renovation','bathroom','Sunshine Coast',95.00),
  ('renovation','bathroom','Toowoomba',95.00),
  ('renovation','bathroom','Townsville',95.00),
  ('renovation','bathroom','Cairns',95.00),
  ('renovation','bathroom','Sydney',95.00),
  ('renovation','bathroom','Newcastle',95.00),
  ('renovation','bathroom','Wollongong',95.00),
  ('renovation','bathroom','Central Coast',95.00),
  ('renovation','bathroom','Melbourne',95.00),
  ('renovation','bathroom','Geelong',95.00),
  ('renovation','bathroom','Perth',95.00),
  ('renovation','bathroom','Adelaide',95.00),
  ('renovation','bathroom','Canberra',95.00)

on conflict do nothing;
